<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta content="IE=edge" http-equiv="X-UA-Compatible" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>Booking Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: #991403;
            color: #fff;
            padding: 20px;
            text-align: center;
        }

        header h1 {
            margin: 0;
        }

        main {
            padding: 20px;
        }

        .address {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
        }

        .section {
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        .invoice-to {
            width: 45%;
            float: left;
        }

        .billing-info {
            width: 45%;
            float: right;
            text-align: right;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            padding: 10px;
            border: 1px solid #ddd;
        }

        th {
            background-color: #f2f2f2;
        }

        .total-row {
            font-weight: bold;
        }

        .title {
            margin-top: 0;
        }

        td.text-end {
            text-align: right;
        }
        td.text-center {
            text-align: center;
        }
    </style>
</head>

<body>
    <header>
        <img src="https://www.kadampuzhadevaswom.com/themes/user/img/website/sree-kadampuzha-bhagavathy-temple-logo.jpg"
            class="navbar-brand-img h-100" alt="main_logo">
    </header>
    <h4 style="text-align: center">Booking Summary BTW {{ \Carbon\Carbon::parse($startDate)->format('d-m-Y') }} and  {{ \Carbon\Carbon::parse($endDate)->format('d-m-Y') }}</h4>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Number of Bookings</th>
                <th>Total Collection</th>
            </tr>
        </thead>
        <tbody>
            @php
                $totalBookings = 0;
                $totalCollection = 0;
            @endphp
            @foreach ($bookings as $bookingData)
                <tr >
                    <td class="text-center">{{ \Carbon\Carbon::parse($bookingData->date)->format('d-m-Y') }}</td>
                    <td class="text-center">{{ $bookingData->bookingCount }}</td>
                    <td class="text-end">{{ $bookingData->totalCollection }}</td>
                </tr>
                @php
                    $totalBookings += $bookingData->bookingCount;
                    $totalCollection += $bookingData->totalCollection;
                @endphp
            @endforeach
            <tr class="total-row">
                <td class="text-center">Total</td>
                <td class="text-center">{{ $totalBookings }}</td>
                <td class="text-end">{{ number_format($totalCollection, 2) }}</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">Generated by: {{ Auth::user()->name }}</td>
                <td colspan="1">Generated at: {{ now()->format('d-m-Y H:i:s') }}</td>
            </tr>
        </tfoot>
    </table>
</body>
</html>
