


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Report</title>
   <link href=" https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        /* Define your PDF styles here */
        body {
            font-family: Arial, sans-serif;
            text-align: center;
        }
        table {
            width: 99%;
            padding-right:5px;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
        }
        .text-right {
            text-align: right; 
        }
        .footer-table {
            width: 100%;
            border-collapse: collapse;
            border: none; 
        }

        .footer-table td, .footer-table th {
            text-align: right; 
            padding: 8px;
            border: 1px solid #fff;
        }
        .footer-table td:nth-child(1) {
            width: 80%; 
            text-align: right; 
        }
        .footer-table td:nth-child(2) {
            width: 30%; 
            text-align: right; 
        }
        .manager-text {
            position: absolute; 
            bottom: 0; 
            right: 0; 
        }
        .card {
    box-shadow: 0 20px 27px 0 rgb(0 0 0 / 5%);
}
.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: 1rem;
}
       
        
    </style>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<header>
    <div class="container">
        <div class="row">     
        <div class="text">
     <div class="mb-4" style="text-align: center;">
<!-- <img src="{{ asset('assets/img/kadampuzha-bhagavathy.png') }}" class="navbar-brand-img h-100" alt="main_logo" style="max-width: 60px;"> -->
<h2 class="mb-1 text-muted">Kadampuzha Bhagavathy Devaswom Guest House</h2>
</div>
<div class="text-muted" style="text-align: center;">
<p class="mb-1">Kadampuzha Devaswom, P.O.Kadampuzha, Malappuram Dist. 676553, Kerala, South India</p>
<p class="mb-1">kadampuzhatemple@gmail.com</p>
<p><i class="uil uil-phone me-1"></i>0494-2618000</p>
</div>
        </div>
    </header>
    <h4 style="text-align: center">Daily Collection  BTW {{ \Carbon\Carbon::parse($startDate)->format('d-m-Y') }} and  {{ \Carbon\Carbon::parse($endDate)->format('d-m-Y') }}</h4>
    <table >
        <thead>
    <tr>
        <th>Receipt Number</th>
        <th>Cash</th>
        <th>Card</th>
        <th>UPI</th>
        <th>Collection</th>
    </tr>
      </thead>
<tbody>
    @php
        $totalCash = 0;
        $totalCards = 0;
        $totalUPI = 0;
        $totalCollection = 0;
    @endphp
    @foreach($bookings as $booking)
        @php
            $totalCash += $booking->cash_collection;
            $totalCards += $booking->card_collection;
            $totalUPI += $booking->upi_collection;
            $totalCollection += $booking->total_collection;
        @endphp
        <tr>
            <td>{{$booking->receipt_number}}</td>
            <td>{{$booking->cash_collection}}</td>
            <td>{{$booking->card_collection}}</td>
            <td>{{$booking->upi_collection}}</td>
            <td>{{$booking->total_collection}}</td>
        </tr>
    @endforeach
    <tr>
        <td><b>Total</b></td>
        <td><b>{{$totalCash}}</b></td>
        <td><b>{{$totalCards}}</b></td>
        <td><b>{{$totalUPI}}</b></td>
        <td><b>{{$totalCollection}}</b></td>
    </tr>

</tbody>
<tfoot>
            <tr>
                <td colspan="3">Generated by: {{ Auth::user()->name }}</td>
                <td colspan="2">Generated at: {{ now()->format('d-m-Y H:i:s') }}</td>
            </tr>
        </tfoot>
    </table>
    <div class="d-print-none mt-4">
<div class="float-end">
<a href="javascript:window.print()" class="btn btn-success me-1"><i class="fa fa-print">Print</i></a>
</div>
</div>
    <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>


